### ISSUE TITLE
jbCrypt license?

### ISSUE THREAD

**Issue by Bertram25** [codebazz/jbcrypt#1]
Hey,

I'd like to use jbCrypt in a commercial project. Can you confirm jbCrypt license terms are the same or similar than found in:
http://www.mindrot.org/projects/jBCrypt/

Could you add a clear license file in this project?
Thanks a lot and best regards,

**Comment by sharif2008** [comment]
jBCrypt is licensed under a ISC/BSD licence. See the LICENSE file for details. http://www.mindrot.org/files/jBCrypt/LICENSE

I have updated the README.md.
